### ISSUE TITLE
The first Type on BaseUseCase should be something like RESULT, not SUCCESS

### ISSUE THREAD

**Issue by luisfernandezbr** [PEBMED/android-base-architecture#4]
https://github.com/PEBMED/android-base-architecture/blob/ba98af18fbaa6de9896f48b15afd35d6a8e085e1/domain/src/main/java/br/com/pebmed/domain/usecases/BaseUseCase.kt#L7

**Comment by rochadaniel** [comment]
[Solved](https://github.com/PEBMED/android-base-architecture/commit/d49fa525cedbd73d2346967012161b7655d27a9d).
