### ISSUE TITLE
Should be possible to return any ERROR on ViewStateResource.Error, instead a forced String

### ISSUE THREAD

**Issue by luisfernandezbr** [PEBMED/android-base-architecture#5]
https://github.com/PEBMED/android-base-architecture/blob/00b63ea516ae9dac57cb43cf5cac681377798519/app/src/main/java/com/example/basearch/presentation/ui/ViewStateResource.kt#L9

**Comment by rochadaniel** [comment]
[Solved](https://github.com/PEBMED/android-base-architecture/commit/e2dae43f6878397220de61e28f377716fb1ff3c3).
